#spring.h2.console.enabled=true
#spring.application.name = courses
#spring.jpa.show-sql = true
#spring.jpa.hibernate.ddl-auto = create
#spring.datasource.url = jdbc:mysql://localhost:3306/boudha?serverTimezone=EST5EDT
#spring.datasource.username = lanre
#spring.datasource.password = jumoke
#spring.datasource.driverClassname = com.mysql.jdbc.Driver
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation = true

spring:
  application:
    name: courses
    datasource:
      url: jdbc:h2:mem:db; DB_CLOSE_DELAY=0;
      username: sa
      password: sa
      driver-class-name: org.h2.Driver
  h2:
    console: true
    path: /h2

---
spring:
  profiles: cloud
  datasource:
    url: jdbc:mysql://localhost:3306/boudha?serverTimezone=EST5EDT
    username: lanre
    password: jumoke
    driverClassname: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
